export const musicList = [
	{
		id: 1,
		name: "Milne Hai Mujhse Aayi",
		artist: "Arjit Singh",
		src: "music-1",
	},
	{
		id: 2,
		name: "Ghoomar",
		artist: "Sherya Goshal",
		src: "music-2",
	},
	{
		id: 3,
		name: "Ae Watan",
		artist: "Sunidhi Chauhan",
		src: "music-3",
	},
	{
		id: 4,
		name: "Apna Time Aayega",
		artist: "Ranveer Singh, Divine",
		src: "music-4",
	},
	{
		id: 5,
		name: "Pachtaoge",
		artist: "Arjit Singh",
		src: "music-5",
	},
	{
		id: 6,
		name: "O Saki Saki",
		artist: "Tulsi Kumar, Neha Kakkar",
		src: "music-6",
	},
	{
		id: 7,
		name: "Chand Sifarish",
		artist: "Shaan, Kailash Kher",
		src: "music-7",
	},
	{
		id: 8,
		name: "Kar Har Maidaan Fateh",
		artist: "Sukhwinder Singh, Sherya Ghoshal",
		src: "music-8",
	},
	{
		id: 9,
		name: "Ek Mulaqat",
		artist: "Altamash Faridi",
		src: "music-9",
	},
	{
		id: 10,
		name: "Filhall",
		artist: "B Praak",
		src: "music-10",
	},
	{
		id: 11,
		name: "Garmi",
		artist: "Badshah, Neha Kakkar",
		src: "music-11",
	},
	{
		id: 12,
		name: "Hasi Ban Gaye",
		artist: "Ami Mishra",
		src: "music-12",
	},
	{
		id: 13,
		name: "Illegal Weapon",
		artist: "Garry Sandhu, Jasmine Sandlas",
		src: "music-13",
	},
	{
		id: 14,
		name: "Jitni Dafa",
		artist: "Yasser Desai",
		src: "music-14",
	},
	{
		id: 15,
		name: "Meri Intkam Dekhegi",
		artist: "Krishna Beuraa",
		src: "music-15",
	},
	{
		id: 16,
		name: "Mercy",
		artist: "Badshah",
		src: "music-16",
	},
	{
		id: 17,
		name: "Mehabooba",
		artist: "Ananya Bhat",
		src: "music-17",
	},
	{
		id: 18,
		name: "Duniyaa",
		artist: "Akhil",
		src: "music-18",
	},
	{
		id: 19,
		name: "Saanson Ko",
		artist: "Arijit Singh, Toshi",
		src: "music-19",
	},
	{
		id: 20,
		name: "Teri Mitti",
		artist: "Arko",
		src: "music-20",
	},
	{
		id: 21,
		name: "Tu Jo Hain",
		artist: "Ankit Tiwari",
		src: "music-21",
	},
	{
		id: 22,
		name: "Banke Hawa Mein Bezubaan Mein",
		artist: "Altmash Faridi",
		src: "music-22",
	},
	{
		id: 23,
		name: "Tu Zaroori",
		artist: "Sunidhi Chauhan, Shaarib Sabri",
		src: "music-23",
	},
	{
		id: 24,
		name: "Teri Ban Jaungi Reprise",
		artist: "Tulsi Kumar",
		src: "music-24",
	},
	{
		id: 25,
		name: "Tum Hi Aana",
		artist: "Jubin Nautiyal, Payal Dev",
		src: "music-25",
	},
	{
		id: 26,
		name: "Dil Mein Ho Tum",
		artist: "Armaan Malik",
		src: "music-26",
	},
	{
		id: 27,
		name: "Woh Ladki Bahut Yaad Aati",
		artist: "Kumar Sanu, Alka Yagnik",
		src: "music-27",
	},
	{
		id: 28,
		name: "Dilbar",
		artist: "Neha Kakkar, Dhvani Bhanushali, Ikka Singh",
		src: "music-28",
	},
	{
		id: 29,
		name: "Agar Tum Saath Ho",
		artist: "Alka Yagnik, Arijit Singh",
		src: "music-29",
	},
	{
		id: 30,
		name: "Jug Jug Jeeve",
		artist: "Sachet Tandon & Parampara Tandon ",
		src: "music-30",
	},
];
